### ISSUE TITLE
can't read ddos.py

### ISSUE THREAD

**Issue by Carlos137ff** [MIISTERC/DDos-Blitz#1]
sed: can't read ddos.py: No such file or directory
mv: cannot stat 'ddos.py': No such file or directory
mv: cannot stat 'ddos': No such file or directory
setup successfully done, now you can execute the script by typing ddos

**Comment by MIISTERC** [comment]
> sed: can't read ddos.py: No such file or directory
> mv: cannot stat 'ddos.py': No such file or directory
> mv: cannot stat 'ddos': No such file or directory
> setup successfully done, now you can execute the script by typing ddos

From the above error it is showing that it can't find the file named ddos.py, first of all to resolve this just check if ddos exists in bin or not , just execute "ls /usr/bin/ddos" if it exists remove it and reinstall the repo and follow all the steps.


If the issue still occurs then no need to run the bash script, now just follow the above steps and reinstall the repo and don't run the setup.sh just type the following commands:-
pip3 install colorama
Python3 ddos.py(make sure you are in the repository directory)

I hope this helps!! I will fix the bug soon!
Thank you.
